version: '3.7'
services:
  api:
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on: 
      - db
  
  db:
    container_name: db
    image: mysql:5.7.29
    restart: always
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer:4.7.5
    restart: always
    ports: 
      - '8080:8080'
    depends_on: 
      - db
